---
include:
  - board: sofle_choc_pro_left
  - board: sofle_choc_pro_right

  # Prospector dongle
  - board: seeeduino_xiao_ble
    shield: sofle_choc_pro_dongle dongle_screen

  # Settings reset
  - board: sofle_choc_pro_left
    shield: settings_reset
  - board: sofle_choc_pro_right
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
